export default {
  SAVE_COURSE: "SAVE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",

  SAVE_AUTHOR: "SAVE_AUTHOR",
  LOAD_AUTHORS: "LOAD_AUTHORS",
  DELETE_AUTHOR: "DELETE_AUTHOR",
};
